services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        SECRET_KEY: ${SECRET_KEY}
        DB_PASSWORD: ${DB_PASSWORD}
    command: gunicorn --bind 0.0.0.0:8000 --pythonpath /app/thedev thedev.wsgi:application
    restart: unless-stopped
    env_file:
      - .env
    environment: # Add these environment variables
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=thedev.settings
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
      - SECURE_SSL_REDIRECT=1

    volumes:
      - static_volume:/app/static
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: postgres_prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:1.25
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    restart: on-failure
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


volumes:
  postgres_data_prod:
  static_volume:
  certbot-etc:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certbot/etc
  certbot-www:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./certbot/www