services:
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --noninteractive --agree-tos -d thedev.com.br --email ${USER_EMAIL} --keep-until-expiring
    depends_on:
      - nginx
    env_file: .env

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/app/static
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    depends_on:
      - web
      - certbot
    command: |
      /bin/sh -c '
      if [ ! -f /etc/letsencrypt/live/thedev.com.br/fullchain.pem ]; then
        echo "No SSL certificate found. Starting in HTTP mode..."
        nginx -g "daemon off;"
      else
        echo "SSL certificate found. Starting in HTTPS mode..."
        while :; do
          sleep 6h
          nginx -s reload
        done & nginx -g "daemon off;"
      fi'

volumes:
  certbot_data:
  certbot_www: