name: Deploy to Production

on:
  push:
    branches: [ master ]

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_HOST: db
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Navigate to the project directory, clone/pull latest code
            if [ -d thedev ]; then
              cd thedev
              git pull origin master
            else
              git clone https://github.com/Tserewara/thedev.git
              cd thedev
            fi

            # Create or update .env.prod with secrets
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > .env.prod
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env.prod
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env.prod
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env.prod

            # Build and restart Docker containers
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d