name: Deploy to Production

on:
  push:
    branches: [ master ]

env:
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_HOST: db
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Copy code to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: .
#          target: /home/${{ secrets.SSH_USER }}/
#
#      - name: Deploy to VPS
#        uses: appleboy/ssh-action@v1
#        with:
#          host: ${{ secrets.VPS_IP }}
#          username: ${{ secrets.SSH_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          script: |
#            cd /home/${{ secrets.SSH_USER }}
#            [ -f .env ] && rm .env
#            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
#            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
#            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
#            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
#            docker compose -f docker-compose.prod.yml build --no-cache
#            docker compose -f docker-compose.prod.yml down
#            docker compose -f docker-compose.prod.yml up -d